// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type DeleteMessage struct {
	ID string `json:"id"`
}

type NewMessage struct {
	Message string `json:"message"`
	UserID  string `json:"userId"`
}

type NewUser struct {
	UserName string `json:"userName"`
}

type UpdateMessage struct {
	ID      string `json:"id"`
	Message string `json:"message"`
}
