// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Message struct {
	ID      string `json:"id"`
	User    *User  `json:"user"`
	Message string `json:"message"`
}

type NewMessage struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}


